# Generated by Django 3.2.4 on 2021-08-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCodePercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='زمان شروع')),
                ('finished', models.DateTimeField(verbose_name='زمان پایان')),
                ('code', models.CharField(max_length=10, verbose_name='کد تخفیف')),
                ('percent', models.FloatField()),
            ],
            options={
                'verbose_name': 'کد تخفیف درصدی',
                'verbose_name_plural': 'کدهای تخفیف درصدی',
            },
        ),
        migrations.CreateModel(
            name='DiscountCodeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='زمان شروع')),
                ('finished', models.DateTimeField(verbose_name='زمان پایان')),
                ('code', models.CharField(max_length=10, verbose_name='کد تخفیف')),
                ('amount', models.FloatField()),
            ],
            options={
                'verbose_name': 'کد تخفیف نقدی',
                'verbose_name_plural': 'کدهای تخفیف نقدی',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ سفارش')),
                ('invoice_complete_date', models.DateTimeField(verbose_name='تاریخ تکمیل سفارش')),
                ('total', models.BigIntegerField(verbose_name='مجموع')),
                ('total_with_discount', models.BigIntegerField(blank=True, null=True, verbose_name='قابل پرداخت')),
                ('status', models.CharField(choices=[('O', 'سفارش'), ('C', 'آماده ارسال')], default='O', max_length=1, verbose_name='وضعیت سفارش')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='accounts.customer', verbose_name='کاربر')),
                ('discount_percent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='percent_code_discount', to='payment.discountcodepercent')),
                ('discount_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='value_code_discount', to='payment.discountcodevalue')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.IntegerField(verbose_name='قیمت واحد')),
                ('quantity', models.IntegerField(verbose_name='تعداد')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.bookmodel', verbose_name='محصول')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.invoice', verbose_name='شماره فاکتور')),
            ],
            options={
                'verbose_name': 'جزییات سفارش',
                'verbose_name_plural': 'جزییات سفارش',
            },
        ),
        migrations.CreateModel(
            name='DiscountValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='مقدارتخفیف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_value', to='book.bookmodel', verbose_name='نام کتاب')),
            ],
            options={
                'verbose_name': 'تخفیف نقدی',
                'verbose_name_plural': 'تخفیف های نقدی',
            },
        ),
        migrations.CreateModel(
            name='DiscountPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(verbose_name='درصد تخفیف')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis_percent', to='book.bookmodel', verbose_name='نام محصول')),
            ],
            options={
                'verbose_name': 'تخفیف درصدی',
                'verbose_name_plural': 'تخفیف های درصدی',
            },
        ),
    ]
