# Generated by Django 3.2.4 on 2021-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.FloatField(default=0, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مقدارتخفیف'),
        ),
    ]
