# Generated by Django 3.2.4 on 2021-08-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مجموع'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_with_discount',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قابل پرداخت'),
        ),
    ]
