# Generated by Django 3.2.4 on 2021-08-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کدهای تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'تخفیف محصول', 'verbose_name_plural': 'تخفیف محصولات'},
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='book',
            new_name='items',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='check_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupons_code', to='payment.coupons'),
        ),
    ]
