# Generated by Django 3.2.4 on 2021-09-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='percent',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='درصد تخفیف'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='value',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='مقدار تخفیف'),
        ),
    ]
