# Generated by Django 3.2.4 on 2021-08-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210815_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_complete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل سفارش'),
        ),
    ]
