# Generated by Django 3.2.4 on 2021-09-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_invoice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت'),
        ),
    ]
