# Generated by Django 3.2.4 on 2021-08-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_invoice_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='مجموع'),
        ),
    ]
