# Generated by Django 3.2.4 on 2021-08-11 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='قیمت')),
                ('price_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='قیمت با تخفیف')),
                ('created', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت کتاب')),
                ('image', models.ImageField(default='0.png', null=True, upload_to='book/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.author', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inventory', models.IntegerField(verbose_name='موجودی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='book.bookmodel', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه ها',
            },
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='categories',
            field=models.ManyToManyField(to='book.CategoryModel', verbose_name='گروه'),
        ),
    ]
