# Generated by Django 3.2.4 on 2021-08-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='categories',
            field=models.ManyToManyField(related_name='category', to='book.CategoryModel', verbose_name='گروه'),
        ),
    ]
