# Generated by Django 3.2.4 on 2021-08-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookmodel_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='price_discount',
            new_name='discount_price',
        ),
    ]
