# Generated by Django 3.2.4 on 2021-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_price_discount_bookmodel_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='discount_price',
            field=models.PositiveBigIntegerField(default=0, verbose_name='قیمت با تخفیف'),
        ),
    ]
